### ISSUE TITLE
Upgrade to jessie and JDK8

### ISSUE THREAD

**Issue by trycoon** [hypriot/rpi-java#2]
Now that "jessie" is available we should upgrade to that version, and also bump JDK-version to 8 since 7 is getting really old.

"openjdk-7-jre" -> "openjdk-8-jre", also update the reference to JAVA_HOME and README.md

Thanks!

**Comment by MathiasRenner** [comment]
Thanks for the pointer, @trycoon! I totally agree with you. Things to do:
  - Update to Jessie
  - Update to very latest Java 8 and to its headless version, since IMHO not many people use Docker with X11
  - Update the reference to `JAVA_HOME` 
  - Update `README.md`

I'll wait for PRs :-)

**Comment by trycoon** [comment]
Done, but I lack access to push my branch of rpi-java. Do I need to make a fork before I send you a PR?
Also, but not related to this issue, how do I get access to GitHub and Docker to provide more packages to Hypriot? I'm thinking about building a Docker image for InfluxDB.

**Comment by MathiasRenner** [comment]
@trycoon Yes, fork it, make your changes and then create a PR.

To publish your image, you need an (free) account at www.dockerhub.com
About adding things to Hypriot, I wanna first have a chat with the team. Will be back soon.

**Comment by trycoon** [comment]
Now there is a PR. Don't hesitate to contact me if you have any questions about the PR.
I have a account on dockerhub.

**Comment by trycoon** [comment]
Master has been updated with jessie and a newer version of OpenJDK-jre-headless, we are now running Java 8!
