### ISSUE TITLE
Illegal instruction (core dumped) using hypriotos-rpi-v1.2.0

### ISSUE THREAD

**Issue by martensjostrand** [hypriot/rpi-java#6]
Hi, 

Ran into this issue when I experimented with docker/java/rpi. Please let me know if you need more details.

## Issue
Ran 
`docker run --rm hypriot/rpi-java:jre-1.8.111 java -version` 
on my Rpi Model B with Hypriot 1.2.0. 
Got the following message:
`/usr/bin/entry.sh: line 86:     6 Illegal instruction     (core dumped) "$CMD" "$@"`

## Full procedure with the output from my Rpi:
> flash --hostname docker1 https://github.com/hypriot/image-builder-rpi/releases/download/v1.2.0/hypriotos-rpi-v1.2.0.img.zip

> ssh pirate@docker1.local

> pirate@docker1 in ~
> $ docker run --rm hypriot/rpi-java:jre-1.8.111 java -version
> Unable to find image 'hypriot/rpi-java:jre-1.8.111' locally
> jre-1.8.111: Pulling from hypriot/rpi-java
> f28608d2221a: Pull complete
> 733cb9bf0c01: Pull complete
> 9c8e6f9eeef4: Pull complete
> 83b44b73b939: Pull complete
> 9ec044b84da5: Pull complete
> f187026830fd: Pull complete
> ac72d8e29c80: Pull complete
> f6146c50c8ad: Pull complete
> c1bcb0da4115: Pull complete
> 54916f25d17d: Pull complete
> Digest: sha256:9e04e5130340d5f1413d2f7c51ce264ae38fe603c47b2410af2fa7241a0537ba
> Status: Downloaded newer image for hypriot/rpi-java:jre-1.8.111
> /usr/bin/entry.sh: line 86:     6 Illegal instruction     (core dumped) "$CMD" "$@"

## Expected
I expected similar results as `rpi-java:jre-1.7.0`  provides:
> $ docker run --rm hypriot/rpi-java:jre-1.7.0 java -version
> Unable to find image 'hypriot/rpi-java:jre-1.7.0' locally
> jre-1.7.0: Pulling from hypriot/rpi-java
> 922c245861e9: Pull complete
> 379c09544a24: Pull complete
> b5374bfa205d: Pull complete
> 8c0e7a40994a: Pull complete
> 4df77b517c01: Pull complete
> a7f97e2b08f7: Pull complete
> 2d971c18088a: Pull complete
> Digest: sha256:c29fbcb6b37ff49bf83a39c926bdaaffbb199ad4ddcfd10259d97e7fc1c472d5
> Status: Downloaded newer image for hypriot/rpi-java:jre-1.7.0
> java version "1.7.0_111"
> OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-2~deb7u1+rpi1)
> OpenJDK Zero VM (build 24.111-b01, interpreted mode)

Is there some problem with hypriot/rpi-java:1.8.111 or am I doing it wrong?
Thanks,
Mårten

**Comment by StefanScherer** [comment]
@martensjostrand please use the official Docker image `openjdk` or some tags there. The official images provide multi-arch images for ARM. 

Example:

```
$ docker run --rm mplatform/mquery openjdk:8-jre-alpine
Image: openjdk:8-jre-alpine
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v6
   - linux/arm64/v8
   - linux/386
   - linux/ppc64le
   - linux/s390x
```
