### ISSUE TITLE
cannot use chmod with this image

### ISSUE THREAD

**Issue by gadieichhorn** [hypriot/rpi-java#7]
I am getting this error when I try to make our main program file executable. any idea what to do?

```
[ERROR] DOCKER> Unable to build image [assembly] : The command '/bin/sh -c chmod 755 /usr/local/karaf/bin/karaf' returned a non-zero code: 1  [The command '/bin/sh -c chmod 755 /usr/local/karaf/bin/karaf' returned a non-zero code: 1 ]
```

tried with chmod and /bin/chmod

I tried with +x and 755. same error

if the build is done on windows (docker for windows) this works
but if done on fedora linux I am getting this error.

thanks in advance.

```
FROM hypriot/rpi-java
EXPOSE 8181 9090
COPY maven /usr/local/karaf/
RUN chmod 755 /usr/local/karaf/bin/karaf
CMD ["/usr/local/karaf/bin/karaf","daemon"]

```

**Comment by firecyberice** [comment]
@gadieichhorn  Is chmod working for other files? Do you have a repo with this example to reproduce this issue? (The COPY command adds some files which are not provided right now.)

**Comment by gadieichhorn** [comment]
@firecyberice this is working fine on Mac or Win 10 (using docker for Mac / Win) but when run native on Fedora I am getting this error. The same exact code using a x64 base image (openjdk:8-jre-alpine) works. So I narrowed this down to this arm image and docker on fedora.

```
FROM openjdk:8-jre-alpine
EXPOSE 8181 9090
COPY maven /usr/local/karaf/
RUN chmod +x /usr/local/karaf/bin/karaf
CMD ["/usr/local/karaf/bin/karaf","daemon"]
```

thanks

**Comment by gadieichhorn** [comment]
any updates on this issue?

**Comment by StefanScherer** [comment]
@gadieichhorn Yes, please use the official Docker image. In the meantime the maintainers of the official Docker images have made a lot of them multi-arch, so you no longer need special ARM images.

You can check this with a small helper image from Docker Captain Phil Estes:

```
$ docker run --rm mplatform/mquery openjdk:8-jre-alpine
Image: openjdk:8-jre-alpine
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v6
   - linux/arm64/v8
   - linux/386
   - linux/ppc64le
   - linux/s390x
```


So your example Dockerfile from above should simply work on a Raspberry Pi.

**Comment by gadieichhorn** [comment]
thanks, the command above worked...
```
HypriotOS/armv7: pirate@black-pearl in /usr
$ docker run --rm mplatform/mquery openjdk:8-jre-alpine
Image: openjdk:8-jre-alpine
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v6
   - linux/arm64/v8
   - linux/386
   - linux/ppc64le
   - linux/s390x
```
I am building the image with fabric8 plugin
```
                                    <build>
                                        <from>openjdk:8-jre-alpine</from>
```
but when running I get this error.
```
standard_init_linux.go:178: exec user process caused "exec format error"
```
when runnign the hypriot image I dont get this error.

**Comment by StefanScherer** [comment]
Do you build it with fabric8 plugin on an Intel machine and then run it on the Raspberry Pi?
This would explain the "exec form at error" which is typical when the architecture does not match.

Anyway you can use the exact name of the offical image from the mquery output above: `linux/arm/v6` will be `arm32v6/` as a prefix to the image name.
 So what happens when you use `FROM arm32v6/openjdk:8-jre-alpine`?

**Comment by StefanScherer** [comment]
Maybe @rhuss can help out with Fabric8 on Raspberry Pi and the new multi-arch openjdk images? :-)

**Comment by rhuss** [comment]
Well, fabric8-maven-plugin does no magic here, it just sends the Dockerfile along with the context in a tar to the Docker daemon it is configured for. 

We could do some more magic, if a single Docker daemon could create images for multiples architectures, in that case only the base image needs to be multi-arch, too (java is arch agnostic, so should be no problem).

@StefanScherer do you know whether this is possible ? Then we could think about adding this to docker-maven-plugin (and inherit this in the fabric8-maven-plugin).

**Comment by StefanScherer** [comment]
@rhuss the Docker API or manifest-tool or docker manifest command does not provide such functionality to build an multi-arch application image from a multi-arch base image.
Current workflow is to build the application for each platform and push it to a registry, then create the new manifest-list and push the manifest-list (= "multi-arch image") to the registry.

To do this in one "docker build" command would be really magical :-)

**Comment by rhuss** [comment]
Ah, ok. So I'm afraid that I then can't help much except to recommend to run f-m-p on every platform separately ...

**Comment by gadieichhorn** [comment]
OK, thank you all.

What I dont get is why an image built on win10 will work even if it is not an ARM system?

using your suggestion I used:                                         
```
<from>arm64v8/openjdk:8-jre-alpine</from>
```

and I can now do a build on Fedora, however, this image will fail to run on Rpi with the same error.
Getting same error after building the image directly on the RPI using fabirc8 docker machine 

```
                        <configuration>
                            <machine>
                                <name>rpi1</name>
                            </machine>
                            <images>
                                <image>
                                    <name>project/arm-app</name>
                                    <build>
                                        <from>arm64v8/openjdk:8-jre-alpine</from>

```

same error
```
HypriotOS/armv7: pirate@black-pearl in ~
$ docker run -i project/arm-app
standard_init_linux.go:178: exec user process caused "exec format error"
```

what am I doing wrong here?

**Comment by StefanScherer** [comment]
The arm64v8 images are only for 64bit ARM, but you have ARMv7 HypriotOS and that runs even the Raspberry Pi in 32bit. So you need the arm32v5, arm32v6 or arm32v7 depending on the availability of the images.
But you also can install a 64bit version of HypriotOS (https://github.com/DieterReuter/image-builder-rpi64/releases) and go with the arm64v8 base images.

Docker 4 Windows and Docker 4 Mac have QEMU emulation enabled for ARM 32 and 64, so you can build and run ARM images on your laptop.

**Comment by gadieichhorn** [comment]
Thanks! that worked nicely.

We are using R-pi  3 so we might be able to move to 64b OS.
